import pandas as pd
import numpy as np
from config import config
from models.linear_models import linerreg, SVR, lassocv, ridgecv, elasticnetcv
from models.tree_models import dectree, random_forest, catboost, xgboost
from preprocessing import work

prep = work()
model_1 = linerreg()
model_2 = SVR()
model_3 = lassocv()
model_4 = ridgecv()
model_5 = elasticnetcv()
model_6 = dectree()
model_7 = random_forest()
model_8 = catboost()
model_9 = xgboost()
print('--import data--')
df_train = pd.read_csv(config.path.train)
print('--import complete, prep now--')
X, y = prep.prep(df = df_train)
print('--prep ends, start train--')
metrics_1 = model_1.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_2 = model_2.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_3 = model_3.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_4 = model_4.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_5 = model_5.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_6 = model_6.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_7 = model_7.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_8 = model_8.train(X_train = X, y = y, folds = 5, repeat = 3)
metrics_9 = model_9.train(X_train = X, y = y, folds = 5, repeat = 3)
print('--linerreg:')
print(f'MSE: {metrics_1['mse'][0]} | MSE std: {metrics_1['mse'][1]}')
print(f'MAE: {metrics_1['mae'][0]} | MAE std: {metrics_1['mae'][1]}')
print(f'r2: {metrics_1['r2']}')
print('--SVR:')
print(f'MSE: {metrics_2['mse'][0]} | MSE std: {metrics_2['mse'][1]}')
print(f'MAE: {metrics_2['mae'][0]} | MAE std: {metrics_2['mae'][1]}')
print(f'r2: {metrics_2['r2']}')
print('--lassocv:')
print(f'MSE: {metrics_3['mse'][0]} | MSE std: {metrics_3['mse'][1]}')
print(f'MAE: {metrics_3['mae'][0]} | MAE std: {metrics_3['mae'][1]}')
print(f'r2: {metrics_3['r2']}')
print('--ridgecv:')
print(f'MSE: {metrics_4['mse'][0]} | MSE std: {metrics_4['mse'][1]}')
print(f'MAE: {metrics_4['mae'][0]} | MAE std: {metrics_4['mae'][1]}')
print(f'r2: {metrics_4['r2']}')
print('--elasticnetcv')
print(f'MSE: {metrics_5['mse'][0]} | MSE std: {metrics_5['mse'][1]}')
print(f'MAE: {metrics_5['mae'][0]} | MAE std: {metrics_5['mae'][1]}')
print(f'r2: {metrics_5['r2']}')
print('--dectree')
print(f'MSE: {metrics_6['mse'][0]} | MSE std: {metrics_6['mse'][1]}')
print(f'MAE: {metrics_6['mae'][0]} | MAE std: {metrics_6['mae'][1]}')
print(f'r2: {metrics_6['r2']}')
print('--random forest')
print(f'MSE: {metrics_7['mse'][0]} | MSE std: {metrics_7['mse'][1]}')
print(f'MAE: {metrics_7['mae'][0]} | MAE std: {metrics_7['mae'][1]}')
print(f'r2: {metrics_7['r2']}')
print('--catboost')
print(f'MSE: {metrics_8['mse'][0]} | MSE std: {metrics_8['mse'][1]}')
print(f'MAE: {metrics_8['mae'][0]} | MAE std: {metrics_8['mae'][1]}')
print(f'r2: {metrics_8['r2']}')
print('--xgboost:')
print(f'MSE: {metrics_9['mse'][0]} | MSE std: {metrics_9['mse'][1]}')
print(f'MAE: {metrics_9['mae'][0]} | MAE std: {metrics_9['mae'][1]}')
print(f'r2: {metrics_9['r2']}')

# cols_with_nans = df_train.columns[df_train.isna().any()].tolist()

# # 2. Очищаем данные
# df_train = prep.prep_for_nan(df = df_train)

# # 3. Строим отчет только по тем колонкам, которые мы запомнили
# df_report = pd.DataFrame({
#     'dtype': df_train[cols_with_nans].dtypes,
#     'unique_values': df_train[cols_with_nans].nunique()
# }, index=cols_with_nans)

# print(df_report)